### ISSUE TITLE
make widget url configurable

### ISSUE THREAD

**Issue by physikerwelt** [ag-gipp/mast-java-demo#10]
the service should also be usable without dependencies to external domains such as math.citeplag.org

**Comment by vstange** [comment]
Do you mean a local installation of the renderer on the server?

**Comment by physikerwelt** [comment]
Yes

On Mar 25, 2017 13:46, "vstange" <notifications@github.com> wrote:

Do you mean a local installation of the renderer on the server?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ag-gipp/mast-java-demo/issues/10#issuecomment-289209615>,
or mute the thread

**Comment by physikerwelt** [comment]
For example the power symbol is not implemented on math.citeplag.org

**Comment by vstange** [comment]
The URL for the Math AST renderer is configurable now. Is the MAST service already running on the test server?

**Comment by physikerwelt** [comment]
yes http://drmf-mast.wmflabs.org/

**Comment by vstange** [comment]
Perfect. URL was entered into the configuration. Demo was restarted.

**Comment by vstange** [comment]
Fixed :).
