### ISSUE TITLE
Implement similarity module

### ISSUE THREAD

**Issue by physikerwelt** [ag-gipp/mast-java-demo#2]
Currently the tool only idenfies identical formulae. However, we also want to visualize similar formulae. The easiest way to do that is to use the same algorithm as the algorithm that is already used for the identical formulae, but transform the formulae first using the conent dictionaly abstraction. (cf.  [Figure 1](http://research.nii.ac.jp/ntcir/workshop/OnlineProceedings11/pdf/NTCIR/Math-2/04-NTCIR11-MATH-SchubotzM.pdf)). The code for the content dictionary abstraction is already availible from [mathosphere](https://github.com/TU-Berlin/mathosphere/blob/master/mathosphere-core/src/main/java/com/formulasearchengine/mathosphere/mml/CMMLInfo.java#L293). 

Task width: This should be doable in just a few hours.

**Comment by physikerwelt** [comment]
I checked comparing \sin x and \cos x by they were not considered as simliar even though they are both from the same cd
http://www.openmath.org/cdindex.html

**Comment by vstange** [comment]
Seems right. I have taken the abstraction method from mathosphere and it requires the attribute "cd" on the MathML node. The MathML from the server does not add this however.

Was this assumption wrong?

**Comment by physikerwelt** [comment]
you need to convert to strict cmml first. There should be a method for that as well.

**Comment by vstange** [comment]
Okay, after our last discussion: strict cmml is finally implemented :).

![auswahl_009](https://cloud.githubusercontent.com/assets/26301768/24134000/af7cd928-0e44-11e7-88f6-b2ec21f82c88.png)

**Comment by physikerwelt** [comment]
well done. I have refactored [mathosphere](https://github.com/TU-Berlin/mathosphere) a bit. Now the functionality you are using is availible from a stand alone library called [MathMLTools](https://github.com/physikerwelt/mathmltools). If you did improvements to the strict cmml extraction can you pleas make a pull request to the new library. By the way, can this issue be closed, or is there anything left to be done?

**Comment by vstange** [comment]
Okay, then this issue is closed :).
