### ISSUE TITLE
Make LaTeXML configuration adjustable from the GUI

### ISSUE THREAD

**Issue by physikerwelt** [ag-gipp/mast-java-demo#3]
It would be interesting to test request with different LaTeXMl configs. Lilke comparing a^b with one rendering configuration to a^b with another configuration.
Two text fields were the config from the YAML file can be entered would be sufficient.

**Comment by vstange** [comment]
Maybe not very elegant but it should work:

![auswahl_010](https://cloud.githubusercontent.com/assets/26301768/24138297/178cbf36-0e5b-11e7-9f3b-f7dbb001effb.png)
