### ISSUE TITLE
Feedback for buttons

### ISSUE THREAD

**Issue by physikerwelt** [ag-gipp/mast-java-demo#7]
At the moment it's somehow difficult for the user to see the effect of the button clicks. It would be nice to show some feedback. Maybe just print std.out to a new window below the current setup.

**Comment by physikerwelt** [comment]
https://github.com/ag-gipp/mast-java-demo/issues/8#issuecomment-289263137
^^
I think that's good first step. While one could invest a log of work on this I think a hint to the user that it's a good idea to look at the java console, or to use a plugin that displays that output in a textfield on the page would be optimal for this technical demo.

**Comment by vstange** [comment]
Since no one actually wants to fiddle around on a demo, I was just thinking to add the suggested text field at the bottom. Maybe add a Button to toggle it like the "Config".

**Comment by vstange** [comment]
Okay, a logging field was added. Version is online :).
