### ISSUE TITLE
Testcase for latexml config

### ISSUE THREAD

**Issue by physikerwelt** [ag-gipp/mast-java-demo#9]
for the input `${\displaystyle\RiemannZeta@{s}=\frac{1}{(1-2^{1-s})\EulerGamma@{s+1}}\Int{0}{\infty}@{x}{\frac{e^{x}x^{s}}{(e^{x}+1)^{2}}}}$` and the config 
```json
{
  "url" : "http://localhost:9999",
  "params" : {
    "whatsin" : "math",
    "whatsout" : "math",
    "includestyles" : "",
    "format" : "xhtml",
    "pmml" :"",
    "cmml" : "",
    "nodefaultresources" : "",
    "linelength" : "90",
    "quiet" : "",
    "preload" : "LaTeX.pool,article.cls,amsmath.sty,amsthm.sty,amstext.sty,amssymb.sty,eucal.sty,DLMFmath.sty,[dvipsnames]xcolor.sty,url.sty,hyperref.sty,[ids]latexml.sty,texvc",
   "stylesheet":"DRMF.xsl"
  }
}
```
a resonable graph should be printed. Maybe that can be a good default config. For the current default I see the following warning in the console:
```
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "localhost:9999": unknown protocol: localhost; nested exception is java.net.MalformedURLException: unknow
```

**Comment by vstange** [comment]
The default-config was on "localhost:9999", where as "http://localhost:9999" would be correct, like in your suggestion.

**Comment by vstange** [comment]
So far I had developed against the web-based LaTeXML on http://gw125.iu.xsede.org:8888. What is the preferred way to include the "DRMF.stv" stylesheet? Use another service or a local installation?

**Comment by physikerwelt** [comment]
ok make
```
{
  "url" : "http://gw125.iu.xsede.org:8888",
  "params" : {
    "whatsin" : "math",
    "whatsout" : "math",
    "includestyles" : "",
    "format" : "xhtml",
    "pmml" :"",
    "cmml" : "",
    "nodefaultresources" : "",
    "linelength" : "90",
    "quiet" : "",
    "preload" : "LaTeX.pool,article.cls,amsmath.sty,amsthm.sty,amstext.sty,amssymb.sty,eucal.sty,DLMFmath.sty,[dvipsnames]xcolor.sty,url.sty,hyperref.sty,[ids]latexml.sty,texvc",
   "stylesheet":"DRMF.xsl"
  }
}
```

**Comment by physikerwelt** [comment]
I uploaded DRMF.xsl to the server.

**Comment by vstange** [comment]
Thank you. Currently the live demo should display the formula right.

Tomorrow I will add system tests against a local installation and http://gw125.iu.xsede.org:8888 and then close the issue.
